### ISSUE TITLE
Missing Scene Flow Clustering

### ISSUE THREAD

**Issue by gs14iitbbs** [aljosaosep/sparse-scene-flow#1]
Th code does not contain the scene flow clustering part as given in the paper "Sparse Scene Flow Segmentation for Moving Object Detection in Urban Environments".

But the code only contains the implementation of finding the sparse flow only.

**Comment by aljosaosep** [comment]
Hi,
Thanks for your comment! Indeed it does not contain the clustering code, it only contains scene flow estimator. Sorry if this was not stated clearly enough in the README -- I will edit it to point this out more clearly.
